---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: bogdanskiy/jenkins-kuber:v2
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 30000
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          emptyDir: {}
